### ISSUE TITLE
System.MissingMethodException when ITwilioRestClient created via DI

### ISSUE THREAD

**Issue by keltex** [twilio/twilio-csharp#768]
### Issue Summary

This is a dotnetcore application running on dotnet 7. When attempting to instatiate a ITwilioRestClient via dependency injection, I get the following exception:

System.MissingMethodException: 'Method not found: 'Void Twilio.Clients.TwilioRestClient..ctor(System.String, System.String, System.String, System.String, Twilio.Http.HttpClient, System.String)'.'

**This is happening on twilio 7.6.0. If I roll back to twilio 7.5.1 the bug does not occur.**

### Steps to Reproduce
1. Nuget to install twilio version 7.6.0
2. Use Configure twilio in startup.cs
3. Attempt to instantiate a ITwilioRestClient via DI

### Code Snippet

Here's my code to create the service in startup.cs

```csharp
services.AddTwilioClient(optionsToConfigure =>
{
    auction4.Services.Utility.TwilioUtil.SetOptions(Configuration, optionsToConfigure);
});
```

Then the exception occurs when my razor page loads:

```csharp
private readonly ITwilioRestClient _twilioClient;
private readonly IConfiguration _configuration;

public TwilioSendModel(IConfiguration configuration, 
    ITwilioRestClient twilioClient)
{
    _twilioClient = twilioClient;
    _configuration = configuration;
}
```

### Exception/Log
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Twilio.Clients.TwilioRestClient..ctor(System.String, System.String, System.String, System.String, Twilio.Http.HttpClient, System.String)'.
  Source=Twilio.AspNet.Core
  StackTrace:
   at Twilio.AspNet.Core.TwilioClientDependencyInjectionExtensions.CreateTwilioClient(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
```

### Technical details:
* twilio-csharp version:  7.6.0
* csharp version: 7

**Comment by Swimburger** [comment]
Changing the signature of a method or constructor is a breaking change. Even if it's a new optional parameter, as you can see above, it requires depending libraries to recompile and release a new version.

@Twilio maintainers, if you add new parameters, provide overloads so the original signature still exists for existing libraries.

**Comment by Daniel15** [comment]
I'm hitting the same issue. Reverting to v7.5.1 worked for me too.

**Comment by AsabuHere** [comment]
This issue is fixed in the codebase and will be part of next release

**Comment by ltctech** [comment]
@Swimburger @AsabuHere 

I updated to Twilio 7.8.0 and Twilio.AspNet.Core 8.1.0 today. Still getting an error:

```
System.MissingMethodException: Method not found: 'Void Twilio.Clients.TwilioRestClient..ctor(System.String, System.String, System.String, System.String, Twilio.Http.HttpClient, System.String, Twilio.AuthStrategies.AuthStrategy)'.
   at Twilio.AspNet.Core.TwilioClientDependencyInjectionExtensions.CreateTwilioClient(IServiceProvider provider)
```

Reverting to Twilio.AspNet.Core 8.0.2 fixes it. Seems both libraries were modified to support the other and now they're again no longer compatible.

**Comment by Daniel15** [comment]
Why aren't these two libraries in the same repo and released concurrently? It's not great to have releases that are incompatible with each other like this.

**Comment by Swimburger** [comment]
> Why aren't these two libraries in the same repo and released concurrently? It's not great to have releases that are incompatible with each other like this.
> […](#)
> On December 5, 2024 6:02:44 PM PST, ltctech ***@***.***> wrote: @Swimburger @AsabuHere I updated to Twilio 7.8.0 and Twilio.AspNet.Core 8.1.0 today. Still getting an error: ``` System.MissingMethodException: Method not found: 'Void Twilio.Clients.TwilioRestClient..ctor(System.String, System.String, System.String, System.String, Twilio.Http.HttpClient, System.String, Twilio.AuthStrategies.AuthStrategy)'. at Twilio.AspNet.Core.TwilioClientDependencyInjectionExtensions.CreateTwilioClient(IServiceProvider provider) ``` Reverting to Twilio.AspNet.Core 8.0.2 fixes it. Seems both libraries were modified to support the other and now they're again no longer compatible. -- Reply to this email directly or view it on GitHub: [#768 (comment)](https://github.com/twilio/twilio-csharp/issues/768#issuecomment-2521923929) You are receiving this because you commented. Message ID: ***@***.***>

Twilio.AspNet is a community project, not officially supported by Twilio.

Regardless, the change that was just made in this repo was another breaking change because the position of the `authstrategy` parameter was moved to the third position.

**Comment by Swimburger** [comment]
Twilio.AspNet has been updated to use the latest version of Twilio C# helper library again.

**Comment by williamdenton** [comment]
I have just been caught by this took - i used the latest libraries for both projects are they are not compatible.

Changing the parameter order is a semver breaking change.

**Comment by williamdenton** [comment]
It looks like 8.1.1 fixes this, but there is no release notes to this effect

I would still advise you add the constructor back to this library to make it backwards compatible. But you are going to have to leave the new one there too. When you next do a major release you can tidy it up. Judging by nuget download counts this hasn't affected may users yet. You can still fix it before more and more people come here to complain.

![image](https://github.com/user-attachments/assets/89d9334d-c4cc-4fb6-afdf-35ad276d4029)
![image](https://github.com/user-attachments/assets/d1b59a0d-4d6a-4b69-86c9-41bf684d3f6d)

**Comment by sbansla** [comment]
I will check this shortly.
